# .github/workflows/deploy.yml

name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # This step is optional if you have no build warnings
      # Vercel's build command often fails if there are warnings.
      # This ensures the build command will succeed.
      - name: Set CI to false
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          # Vercel authentication token
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          
          # GitHub token is required for the action to work
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Vercel organization ID
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          
          # Vercel project ID
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          
          # The directory where your frontend code is located
          vercel-cwd: frontend